[workspace]
resolver = "2"
members = ["finni", "short_clip", "shared"]
default-members = ["short_clip", "shared"]

[workspace.dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
mime_guess = "2.0.4"
